services:
  httpbin:
    image: kennethreitz/httpbin
  nginx:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./log.js:/etc/nginx/njs/log.js"
    ports:
      - 8080:8080
    depends_on:
      - httpbin
