services:
  mosquitto-broker:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mosquitto-broker
  sub_client:
    image: hivemq/mqtt-cli
    command: [ "sub", "-t", "test", "-h", "proxy", "-p", "1883" ]
    depends_on:
      - proxy
  pub_client:
    build:
      context: ./pub_client
    depends_on:
      - proxy
